// <auto-generated />
using System;
using JobExecutorModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JobExecutorModel.data
{
    [DbContext(typeof(JobDbContext))]
    partial class JobContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JobExecutorModel.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Enqueued")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("JobExecutionDuration")
                        .HasColumnType("time");

                    b.Property<string>("JobExecutionMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobExecutor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobStatus")
                        .HasColumnType("int");

                    b.HasKey("JobId");

                    b.ToTable("Job");
                });
#pragma warning restore 612, 618
        }
    }
}
